spring.datasource.url=jdbc:postgresql://localhost:5432/couture

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=couture
spring.servlet.multipart.enabled=true
spring.jpa.show-sql=false
spring.mvc.pathmatch.matching-strategy = ANT_PATH_MATCHER
