package com.sali.salicouture.service.dto.enums;

public enum Message {
    SUCCES, CLIENT_ALREADY_EXIST, CLIENT_NOT_EXIST, COMMANDE_NOT_EXIST, MESURE_STANDARD_VESTE_NOT_EXIST, MESURE_STANDARD_PANTALON_NOT_EXIST, MESURE_STANDARD_CHEMISE_NOT_EXIST, MESURE_NOT_EXIST
}
